// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4oWBB6AExAmefxxaxqy9YkuLrpgKgx-U',
    appId: '1:334338111879:web:dc24b58cb6366a5afffb22',
    messagingSenderId: '334338111879',
    projectId: 'chat-app-52b6f',
    authDomain: 'chat-app-52b6f.firebaseapp.com',
    storageBucket: 'chat-app-52b6f.firebasestorage.app',
    measurementId: 'G-PF385LT023',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh9TKGVppGUXNKAm69lqQF_bpe58D2Vm8',
    appId: '1:334338111879:android:24cd09338fadb103fffb22',
    messagingSenderId: '334338111879',
    projectId: 'chat-app-52b6f',
    storageBucket: 'chat-app-52b6f.firebasestorage.app',
  );
}
